(cl:in-package utils-msg)
(cl:export '(HEADER-VAL
          HEADER
          LS_PISTON_ATHEAD-VAL
          LS_PISTON_ATHEAD
          LS_PISTON_ATTAIL-VAL
          LS_PISTON_ATTAIL
          LS_MASS_SHIFTER_ATHEAD-VAL
          LS_MASS_SHIFTER_ATHEAD
          LS_MASS_SHIFTER_ATTAIL-VAL
          LS_MASS_SHIFTER_ATTAIL
          ALTIMETER_IN_METRES-VAL
          ALTIMETER_IN_METRES
          ALTIMETER_IN_FEET-VAL
          ALTIMETER_IN_FEET
          ALTIMETER_IN_FATHOMS-VAL
          ALTIMETER_IN_FATHOMS
          ALARM_1_HEAD-VAL
          ALARM_1_HEAD
          ALARM_2_HEAD-VAL
          ALARM_2_HEAD
          ALARM_3_HEAD-VAL
          ALARM_3_HEAD
))