# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from utils/BoardARM1Status.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class BoardARM1Status(genpy.Message):
  _md5sum = "0a28fffcadb31a721a41b0390a47c8af"
  _type = "utils/BoardARM1Status"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header header

uint8 ls_piston_athead
uint8 ls_piston_attail
uint8 ls_mass_shifter_athead
uint8 ls_mass_shifter_attail
float64 altimeter_in_metres
float64 altimeter_in_feet
float64 altimeter_in_fathoms
uint8 alarm_1_head
uint8 alarm_2_head
uint8 alarm_3_head
================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id
"""
  __slots__ = ['header','ls_piston_athead','ls_piston_attail','ls_mass_shifter_athead','ls_mass_shifter_attail','altimeter_in_metres','altimeter_in_feet','altimeter_in_fathoms','alarm_1_head','alarm_2_head','alarm_3_head']
  _slot_types = ['std_msgs/Header','uint8','uint8','uint8','uint8','float64','float64','float64','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,ls_piston_athead,ls_piston_attail,ls_mass_shifter_athead,ls_mass_shifter_attail,altimeter_in_metres,altimeter_in_feet,altimeter_in_fathoms,alarm_1_head,alarm_2_head,alarm_3_head

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BoardARM1Status, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ls_piston_athead is None:
        self.ls_piston_athead = 0
      if self.ls_piston_attail is None:
        self.ls_piston_attail = 0
      if self.ls_mass_shifter_athead is None:
        self.ls_mass_shifter_athead = 0
      if self.ls_mass_shifter_attail is None:
        self.ls_mass_shifter_attail = 0
      if self.altimeter_in_metres is None:
        self.altimeter_in_metres = 0.
      if self.altimeter_in_feet is None:
        self.altimeter_in_feet = 0.
      if self.altimeter_in_fathoms is None:
        self.altimeter_in_fathoms = 0.
      if self.alarm_1_head is None:
        self.alarm_1_head = 0
      if self.alarm_2_head is None:
        self.alarm_2_head = 0
      if self.alarm_3_head is None:
        self.alarm_3_head = 0
    else:
      self.header = std_msgs.msg.Header()
      self.ls_piston_athead = 0
      self.ls_piston_attail = 0
      self.ls_mass_shifter_athead = 0
      self.ls_mass_shifter_attail = 0
      self.altimeter_in_metres = 0.
      self.altimeter_in_feet = 0.
      self.altimeter_in_fathoms = 0.
      self.alarm_1_head = 0
      self.alarm_2_head = 0
      self.alarm_3_head = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4B3d3B().pack(_x.ls_piston_athead, _x.ls_piston_attail, _x.ls_mass_shifter_athead, _x.ls_mass_shifter_attail, _x.altimeter_in_metres, _x.altimeter_in_feet, _x.altimeter_in_fathoms, _x.alarm_1_head, _x.alarm_2_head, _x.alarm_3_head))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 31
      (_x.ls_piston_athead, _x.ls_piston_attail, _x.ls_mass_shifter_athead, _x.ls_mass_shifter_attail, _x.altimeter_in_metres, _x.altimeter_in_feet, _x.altimeter_in_fathoms, _x.alarm_1_head, _x.alarm_2_head, _x.alarm_3_head,) = _get_struct_4B3d3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_4B3d3B().pack(_x.ls_piston_athead, _x.ls_piston_attail, _x.ls_mass_shifter_athead, _x.ls_mass_shifter_attail, _x.altimeter_in_metres, _x.altimeter_in_feet, _x.altimeter_in_fathoms, _x.alarm_1_head, _x.alarm_2_head, _x.alarm_3_head))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 31
      (_x.ls_piston_athead, _x.ls_piston_attail, _x.ls_mass_shifter_athead, _x.ls_mass_shifter_attail, _x.altimeter_in_metres, _x.altimeter_in_feet, _x.altimeter_in_fathoms, _x.alarm_1_head, _x.alarm_2_head, _x.alarm_3_head,) = _get_struct_4B3d3B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_4B3d3B = None
def _get_struct_4B3d3B():
    global _struct_4B3d3B
    if _struct_4B3d3B is None:
        _struct_4B3d3B = struct.Struct("<4B3d3B")
    return _struct_4B3d3B
